== Introduction

The number of citizen science projects is constantly growing. Local, national, and international platforms feature new projects almost every month, resulting in huge number of observations. If these are to contribute to knowledge beyond short term project outputs these observations need to be gathered and potentially stored in Web accessible databases. For this data to fulfil that potential it needs to fulfil various aspects of comparability with other similar data, and this to be transparent as an aid to data discovery. Any automated integration of such data will require machine-readable metadata about the level of compatibility of such data. This paper describes those aspects of 'data interoperability'. It focuses on the concept of a scalable approach to "citizen science application profiles" using a standardized information model that ensures syntactic and semantic understanding of citizen science data collected by arbitrary sampling campaigns. Data compliant to this information model can be discovered and accessed through standardized Web interfaces and therefore easily integrated into any data processing environment or compared to any other data set. It is emphasized that the application profile approach described in this paper is one out of two possible solutions. The second is briefly addressed and will be documented in detail in future publications.

===	Scope
This document focuses on three aspects. First, it describes common design decisions as they currently occur in many citizen science sampling campaigns. Second, it provides a data model that addresses most of the current interoperability issues by applying available models and technologies. Third, it outlines a path ahead that describes future solutions that further improve the level of interoperability.


===	Document contributor contact points

All questions regarding this document should be directed to the editor or the contributors:


.Contacts
[width="80%",options="header"]
|====================
|Name |Organization
|Ingo Simonis | OGC
|Rob Atkinson | OGC
|====================


=== Future Work
The inherent challenges in defining a "one size fits all" approach have led to the identification of a need for, and a possible standards-based solution to, a flexible and scalable methdology for describing the semantic interoperability of data and how this is then realised in standardised data structures.
This document is thus a first step towards a new approach to interoperability in heterogenous environments that supports semantic interoperability managed by the communities of practice. The concept needs further research and should be explored in other domains to evaluate its universal applicability.

=== Forward

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
