[[overview]]
== Standardized Information Models to Optimize Exchange, Reusability and Comparability of Citizen Science Data

After a short <<CitizenScienceIntroduction,introduction>>, this engineering report discusses the typical <<CitizenScienceProcess,citizen science sampling campaign formalization and execution process>> to allow understanding the full set of requirements that needs to be fulfilled by citizen science data in order to maximize reuse and comparability. It then focuses on the <<CitizenScienceApplicationProfile,citizen science application profile>>, an information model that allows the integration of citizen science data in new contexts without risking semantically incorrect use or interpretation. The model itself makes use of several other OGC standards and can be implemented and serialized in various ways, such as XML or JSON, or Semantic Web approaches based on triples and links. Here, focus is on XML exclusively.

The paper describes how to encode citizen science data in an efficient way. It does not define an application schema with value or other types of constraints. Instead, it should be considered as a guide that helps survey managers to share their data in an efficient way. For that reason, this report describes the usage of O&M and the derived citizen science profile for <<CitizenScienceModels, single>> and <<CitizenScienceCollections,aggregated>> observations and addresses a number of semantic interoperability aspects.

The paper concludes with an outlook on <<EnhancedInteroperability,future interoperability profile concepts>> that shall help simplifying the usage of specialized data models, support the automatic setup of data collection campaigns, and ensure shared semantics in heterogeneous environments.
